version: '3.8'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh "utils/run_local.sh"
    volumes:
      - ./:/usr/src/app
    links:
     - test_db
    ports:
     - "80:80"
    environment:
      - DEBUG=True
      - ENVIRONMENT=test
      - DJANGO_SETTINGS_MODULE=gidsey.settings.test
      - DATABASE_URL=${DATABASE_URL_TEST}
      - SECRET_KEY=${SECRET_KEY}
      - BASE_URL=http://localhost
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}

  test_db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
