# Generated by Django 3.2.10 on 2022-01-03 17:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('photo_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCollection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=100)),
                ('content', wagtail.core.fields.StreamField([('photo_collection_block', wagtail.core.blocks.StructBlock([('left_image', wagtail.images.blocks.ImageChooserBlock(help_text='add left-hand image', required=True)), ('right_image', wagtail.images.blocks.ImageChooserBlock(help_text='add right-hand image', required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
