# Generated by Django 3.2.10 on 2022-01-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('photo_collection', '0003_auto_20220103_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocollectionindexpage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
