# Generated by Django 3.2.10 on 2022-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_collection', '0005_auto_20220103_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocollection',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
