# Generated by Django 4.0.3 on 2022-04-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('photo_collection', '0008_photodetail_delete_photodetailpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoDetail',
            new_name='PhotoDetailPage',
        ),
    ]
