# Generated by Django 4.0.6 on 2022-07-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220707_1638'),
        ('photo_collection', '0010_photocollection_fb_og_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocollection',
            name='fb_og_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage', verbose_name='Facebook image'),
        ),
        migrations.AlterField(
            model_name='photocollection',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage'),
        ),
        migrations.AlterField(
            model_name='photocollection',
            name='twitter_card_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage'),
        ),
        migrations.AlterField(
            model_name='photocollectionindexpage',
            name='fb_og_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage', verbose_name='Facebook image'),
        ),
        migrations.AlterField(
            model_name='photocollectionindexpage',
            name='twitter_card_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage'),
        ),
    ]
