# Generated by Django 4.0.6 on 2022-07-14 15:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('photo_collection', '0012_delete_photodetailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocollection',
            name='content',
            field=wagtail.fields.StreamField([('photo_collection_block', wagtail.blocks.StructBlock([('left_image', wagtail.images.blocks.ImageChooserBlock(help_text='add left-hand image', required=True)), ('right_image', wagtail.images.blocks.ImageChooserBlock(help_text='add right-hand image', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
