# Generated by Django 3.2.9 on 2021-11-22 11:37

import base.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add title', required=False)), ('text', base.blocks.SimpleRichTextBlock(help_text='add text', required=False))])), ('section_head', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add section title', required=False))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='add image', required=False))]))], blank=True, null=True),
        ),
    ]
