# Generated by Django 3.2.9 on 2021-11-23 13:52

import base.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add title', required=False)), ('text', base.blocks.SimpleRichTextBlock(help_text='add text', required=False))])), ('section_head', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add section title', required=False))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='add image', required=False))])), ('two_images', wagtail.core.blocks.StructBlock([('left_image', wagtail.images.blocks.ImageChooserBlock(help_text='add left-hand image', required=False)), ('right_image', wagtail.images.blocks.ImageChooserBlock(help_text='add right-hand image', required=False))])), ('two_thirds_one_third', wagtail.core.blocks.StructBlock([('left_image', wagtail.images.blocks.ImageChooserBlock(help_text='add left-hand image', required=False)), ('right_image', wagtail.images.blocks.ImageChooserBlock(help_text='add right-hand image', required=False))])), ('one_third_two_thirds', wagtail.core.blocks.StructBlock([('left_image', wagtail.images.blocks.ImageChooserBlock(help_text='add left-hand image', required=False)), ('right_image', wagtail.images.blocks.ImageChooserBlock(help_text='add right-hand image', required=False))]))], blank=True, null=True),
        ),
    ]
