# Generated by Django 3.2.9 on 2021-12-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211201_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='gallery_description',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='gallery_title',
        ),
    ]
