# Generated by Django 3.2.9 on 2021-12-01 14:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211201_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageGalleryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('gallery_title', models.CharField(blank=True, max_length=100, null=True)),
                ('gallery_description', models.CharField(blank=True, max_length=250, null=True)),
                ('gallery_info', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_info', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
