# Generated by Django 4.0.4 on 2022-05-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0015_alter_blogpagetag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='fb_og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Facebook card image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_img_alt_text',
            field=models.CharField(blank=True, help_text='Social image alt text - maximum 100 characters', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='twitter_card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
