# Generated by Django 4.0.4 on 2022-05-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0016_blogpage_fb_og_image_blogpage_social_img_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='fb_og_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Facebook image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='twitter_card_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
