# Generated by Django 4.0.3 on 2022-04-06 17:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('preview_pane_block', wagtail.core.blocks.StructBlock([('destination', wagtail.core.blocks.PageChooserBlock(help_text='choose the page to link to', required=True)), ('preview_image', wagtail.images.blocks.ImageChooserBlock(help_text='add a square image here', required=True))]))], blank=True, null=True),
        ),
    ]
