# Generated by Django 4.0.6 on 2022-07-14 15:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_singlephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('preview_pane_block', wagtail.blocks.StructBlock([('preview_image', wagtail.images.blocks.ImageChooserBlock(help_text='add a square image here', required=True)), ('destination', wagtail.blocks.PageChooserBlock(help_text='choose the page to link to', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
