# Generated by Django 4.0.4 on 2022-05-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='fb_og_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Facebook image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='social_img_alt_text',
            field=models.CharField(blank=True, help_text='Social image alt text - maximum 100 characters', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_card_image',
            field=models.ForeignKey(blank=True, help_text='Suggested size: 1200px x 628px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
