# Generated by Django 3.2.9 on 2021-11-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Webiste name', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Your email address', max_length=254, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Your Twitter username, without the @', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Your Instagram username, without the @', max_length=255, null=True)),
                ('flickr', models.URLField(blank=True, help_text='Your Flickr homepage URL', null=True)),
                ('glass', models.URLField(blank=True, help_text='Your Glass profile page URL', null=True)),
                ('favicon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
