# Generated by Django 4.0.5 on 2022-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gidsimage_customrendition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gidsimage',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
