# Generated by Django 4.0.5 on 2022-07-05 14:25

from django.db import migrations


def copy_images_to_custom_table(apps, schema_editor):
    wagtail_image_model = apps.get_model('wagtailimages', 'Image')
    extended_image_model = apps.get_model('base', 'GidsImage')
    db_alias = schema_editor.connection.alias
    images = wagtail_image_model.objects.using(db_alias).all()
    new_images = []
    for image in images:
        new_images.append(extended_image_model(id=image.id,
                                               title=image.title,
                                               file=image.file,
                                               width=image.width,
                                               height=image.height,
                                               created_at=image.created_at,
                                               focal_point_x=image.focal_point_x,
                                               focal_point_y=image.focal_point_y,
                                               focal_point_width=image.focal_point_width,
                                               focal_point_height=image.focal_point_height,
                                               file_size=image.file_size,
                                               file_hash=image.file_hash,
                                               collection=image.collection,
                                               uploaded_by_user=image.uploaded_by_user, ))

    extended_image_model.objects.using(db_alias).bulk_create(new_images)


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0004_alter_gidsimage_slug'),
    ]

    operations = [
        migrations.RunPython(copy_images_to_custom_table)
    ]
