# Generated by Django 4.0.5 on 2022-07-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220705_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gidsimage',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='favicon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='site_icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.gidsimage'),
        ),
    ]
