# Generated by Django 4.0.6 on 2022-07-07 17:14

from django.db import migrations
from base import wagtail_hooks
wagtail_hooks.register_signal_handlers()


def save_slugs_on_existing_images(apps, schema_editor):
    extended_image_model = apps.get_model('base', 'GidsImage')
    for image in extended_image_model.objects.all():
        image.title = image.title
        image.save()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0009_auto_20220707_1638'),
    ]

    operations = [
        migrations.RunPython(save_slugs_on_existing_images)
    ]
