# Generated by Django 4.0.6 on 2022-07-07 17:14

from django.db import migrations


def save_slugs_on_existing_images(apps, schema_editor):
    extended_image_model = apps.get_model('base', 'GidsImage')
    images = extended_image_model.objects.all()
    for image in images:
        image.width = image.width
        image.save()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0009_auto_20220707_1638'),
    ]

    operations = [
        migrations.RunPython(save_slugs_on_existing_images)
    ]
