# Generated by Django 4.0.6 on 2022-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220707_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='gidsimage',
            name='copyright',
            field=models.CharField(default='Chris Guy', max_length=100),
        ),
    ]
